# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "germ"
version = "0.4.8"
authors = ["Fuwn <contact@fuwn.me>"]
edition = "2021"
description = "The Ultimate Gemini Toolkit."
documentation = "https://docs.rs/germ"
readme = "README.md"
homepage = "https://github.com/gemrest/germ"
repository = "https://github.com/gemrest/germ"
license = "MIT OR Apache-2.0"
keywords = ["gemini", "parser", "lexer", "markdown", "converter"]
categories = ["encoding"]
rust-version = "1.83.0"

[features]
ast = []
blocking = ["rustls", "webpki-roots", "url", "anyhow"]
convert = ["ast"]
default = ["ast", "convert", "meta", "request"]
macros = ["ast", "convert"]
meta = []
request = ["rustls", "webpki-roots", "url", "anyhow", "tokio", "tokio-rustls"]
quick = []
example-gemtext = []

[[example]]
name = "ast"
required-features = ["ast", "example-gemtext"]

[[example]]
name = "ast_to_gemtext"
required-features = ["ast", "example-gemtext"]

[[example]]
name = "html"
required-features = ["convert", "example-gemtext"]

[[example]]
name = "markdown"
required-features = ["convert", "example-gemtext"]

[[example]]
name = "meta"
required-features = ["meta"]

[[example]]
name = "request"
required-features = ["request"]

[[example]]
name = "request_blocking"
required-features = ["blocking"]

[[example]]
name = "request_blocking_to_gemtext_from_ast"
required-features = ["ast", "blocking"]

[dependencies]
anyhow = { version = "1.0.98", optional = true } # `Result`
rustls = { version = "0.21.12", optional = true } # TLS
webpki-roots = { version = "1.0.9", optional = true } # CA certificates
tokio-rustls = { version = "0.24.1", optional = true } # Non-blocking TLS
tokio = { version = "1.45.1", optional = true, default-features = false, features = [
  "net",
  "io-util",
  "rt-multi-thread",
  "macros",
  "time",
] } # Non-blocking I/O
url = { version = "2.5.4", optional = true } # URL Validation

[dev-dependencies]
rcgen = "=0.12.1"
