# ------------
# | Wrappers |
# ------------
[tasks.fmt]
args = ["fmt"]
command = "cargo"
toolchain = "nightly"

[tasks.check]
args = ["check", "--all-features"]
command = "cargo"

[tasks.clippy]
args = ["clippy", "--all-features"]
command = "cargo"

[tasks.test]
args = ["test", "--all-features"]
command = "cargo"

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]
workspace = false

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]
workspace = false
