name: Check ✅
on:
  workflow_dispatch:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v7
      - name: Test 🧪
        run: |
          cargo test
          cargo test --all-features
          cargo test --no-default-features
          for feature in ast blocking convert macros meta quick request; do
            cargo test --no-default-features --features "$feature"
          done
      - name: Clippy 📎
        run: cargo clippy --all-features --all-targets -- -D warnings
